TNT-39261 [ODD] Implement context providers + geo lookup
adobe/target-dotnet-sdk pull request #5
Opened 2021-03-01 17:17 UTC by XDex

## Description

TNT-39261 [ODD] Implement context provider
TNT-39266  [ODD] Implement geo provider

## Related Issue

https://jira.corp.adobe.com/browse/TNT-39261
https://jira.corp.adobe.com/browse/TNT-39266

2021-03-03 08:48 UTC, artur-ciocanu requested changes
@XDex overall looks good, but there is no a single test. The functionality that you have added for collators and cookier parsing etc, could be tested via unit tests, so please add the required tests.

2021-03-03 08:48 UTC, artur-ciocanu commented on Source/Adobe.Target.Client/Util/MurmurHash3.cs
> +
Please rename to `HashUnencodedChars()`

2021-03-06 13:48 UTC, XDex commented
@artur-ciocanu Please take another look when you have a moment.. Thx!

2021-03-10 09:44 UTC, artur-ciocanu approved these changes
@XDex it looks good. However I am not really fond of all the code related to domain parsing that doesn't have a single unit test. The code is not trivial, so I would expect tests that over all the domain parsing and public suffix list related logic.

2021-03-10 10:18 UTC, merged